services:
  - type: web
    name: spotyload-backend-flask
    env: python
    region: oregon
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py  
    autoDeploy: true
    envVars: []  
